#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oci-osb-binding-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: oci-osb
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: oci-osb-role-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
